branch-defaults:
  main:
    environment: organizers-microservice-env
    group_suffix: null
global:
  application_name: organizers-microservice-app
  default_ec2_keyname: coms6156-aws-ec2-key-pair
  default_platform: Python 3.7
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: coms6156
  workspace_type: Application
